jenkins:
  container_name: jenkins
  build: "chrisharripaul/purchasing-bot"
  ports:
    - "8080:8080"
  environment:
    - JAVA_OPTS:-Djava.awt.headless=true
  volumes:
    - jenkinsvolume:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock